import { Link } from "react-router-dom";

import EnterpriseLegalPageShell from "../components/EnterpriseLegalPageShell";

const today = new Intl.DateTimeFormat("en-US", {
  month: "long",
  day: "numeric",
  year: "numeric",
}).format(new Date());

const PrivacyPolicyPage = () => {
  return (
    <EnterpriseLegalPageShell
      eyebrow="Privacy policy"
      title="Privacy Policy"
      subtitle="How TechnoSthan handles information shared through our website, forms, and support channels."
      lastUpdated={today}
      metaTitle="Privacy Policy | TechnoSthan"
      metaDescription="Read how TechnoSthan collects, uses, stores, and protects information shared through the public website and contact flows."
      canonicalPath="/privacy"
    >
      <section className="legal-enterprise__section" data-legal-reveal>
        <h2>Introduction</h2>
        <div className="legal-enterprise__body">
          <p>
            This Privacy Policy explains how TechnoSthan handles information provided through
            the public website, contact forms, newsletter fields, and related communication
            surfaces. We keep the policy focused on the information that the site actually
            collects or may reasonably process during normal use.
          </p>
          <p>
            By using the website, you agree that your information may be processed for the
            purposes described below. If you do not want to share information, you can choose
            not to submit forms or contact the team through the public channels.
          </p>
        </div>
      </section>

      <section className="legal-enterprise__section" data-legal-reveal>
        <h2>Information We Collect</h2>
        <div className="legal-enterprise__body">
          <p>Depending on how you use the site, we may collect the following information:</p>
          <ul>
            <li>Name</li>
            <li>Email address</li>
            <li>Phone number</li>
            <li>Company name</li>
            <li>Messages or enquiry details</li>
            <li>Uploaded files you choose to send</li>
            <li>Cookies and preference signals</li>
            <li>Analytics data, if enabled in the deployed environment</li>
            <li>Device and browser information</li>
            <li>IP address and session information</li>
          </ul>
          <p>
            We do not claim to collect information that the website does not request or process.
            Any collection is limited to the data that is provided directly, generated by the
            browser, or required for site operation and security.
          </p>
        </div>
      </section>

      <section className="legal-enterprise__section" data-legal-reveal>
        <h2>How We Use Information</h2>
        <div className="legal-enterprise__body">
          <ul>
            <li>Responding to enquiries and project requests</li>
            <li>Improving website functionality and usability</li>
            <li>Supporting communication and follow-up</li>
            <li>Securing forms, uploads, and public interactions</li>
            <li>Providing maintenance and support</li>
            <li>Reviewing analytics when the site is configured to use them</li>
          </ul>
        </div>
      </section>

      <section className="legal-enterprise__section" data-legal-reveal>
        <h2>Cookies</h2>
        <div className="legal-enterprise__body">
          <p>
            The website may use essential cookies or similar technologies needed for basic
            functionality, preference storage, and performance measurement. If analytics or
            preference cookies are enabled in the future, they will be used to understand how the
            public site is used and to improve the experience.
          </p>
          <p>
            We do not claim advertising-cookie usage unless that functionality is actually
            introduced.
          </p>
        </div>
      </section>

      <section className="legal-enterprise__section" data-legal-reveal>
        <h2>Data Security</h2>
        <div className="legal-enterprise__body">
          <p>
            TechnoSthan uses reasonable security measures to protect information in transit and
            at rest where supported by the deployed environment. Those measures may include
            transport encryption, authentication, access control, and operational safeguards.
          </p>
          <p>
            No online system can promise absolute security, so we cannot guarantee that data will
            never be exposed, intercepted, or misused.
          </p>
        </div>
      </section>

      <section className="legal-enterprise__section" data-legal-reveal>
        <h2>Third Party Services</h2>
        <div className="legal-enterprise__body">
          <p>
            The public website may rely on third-party infrastructure when the deployment is
            configured to do so. One service that is already integrated in the product stack is:
          </p>
          <ul>
            <li>Cloudinary for image and upload handling when configured</li>
          </ul>
          <p>
            Any additional service providers used by a specific deployment will depend on the
            environment in which TechnoSthan is hosted.
          </p>
        </div>
      </section>

      <section className="legal-enterprise__section" data-legal-reveal>
        <h2>User Rights</h2>
        <div className="legal-enterprise__body">
          <ul>
            <li>Request access to your information</li>
            <li>Request correction of inaccurate information</li>
            <li>Request deletion where legally and operationally possible</li>
            <li>Ask questions about how the data is used</li>
          </ul>
        </div>
      </section>

      <section className="legal-enterprise__section" data-legal-reveal>
        <h2>Children Privacy</h2>
        <div className="legal-enterprise__body">
          <p>
            TechnoSthan does not intentionally target children under 13. If a parent or guardian
            believes a child has submitted information through the website, please contact the
            team so the matter can be reviewed.
          </p>
        </div>
      </section>

      <section className="legal-enterprise__section" data-legal-reveal>
        <h2>Policy Updates</h2>
        <div className="legal-enterprise__body">
          <p>
            We may update this Privacy Policy from time to time to reflect changes in the site,
            services, or applicable requirements. When updates are made, the revised version will
            be published on this page with a new last-updated date.
          </p>
        </div>
      </section>

      <section className="legal-enterprise__section legal-enterprise__section--contact" data-legal-reveal>
        <h2>Contact</h2>
        <div className="legal-enterprise__body">
          <p>
            For questions about privacy or data handling, contact TechnoSthan using the verified
            public channels listed in the side panel or through the main contact page.
          </p>
          <Link to="/contact" className="btn-secondary legal-enterprise__inline-link">
            Go to contact page
          </Link>
        </div>
      </section>
    </EnterpriseLegalPageShell>
  );
};

export default PrivacyPolicyPage;

