services:
  - type: web
    name: technosthan-backend
    runtime: node
    plan: free
    buildCommand: |
      cd frontend
      npm install --include=dev
      npm run build
      cd ../backend
      npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ih.technosthan.com
      - key: BACKEND_PUBLIC_URL
        value: https://technosthan-website-2.onrender.com
      - key: VITE_API_URL
        value: https://technosthan-website-2.onrender.com/api
      - key: DATABASE_URL
        fromDatabase:
          name: technosthan-db
          property: connectionString
